{"sections":[],"metadata":{"modules":[{"name":"MoyasarSdk"}],"title":"MoyasarSdk","role":"collection","roleHeading":"Framework","externalID":"MoyasarSdk","symbolKind":"module"},"kind":"symbol","hierarchy":{"paths":[[]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk"},"topicSections":[{"title":"Classes","generated":true,"identifiers":["doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApplePayService","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/CreditCardViewModel","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/MoyasarLanguageManager","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/PaymentService","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/STCPayViewModel"],"anchor":"Classes"},{"anchor":"Structures","identifiers":["doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiApplePaySource","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiCreditCardSource","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiError","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiPayment","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiPaymentRequest","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiSTCPaySource","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiToken","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiTokenRequest","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApplePayPaymentMethod","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApplePayPaymentPass","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApplePayToken","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/CreditCardView","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/PaymentAuthView","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/PaymentRequest","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/STCPayView","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/StcOtpRequest","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/WebViewPaymentInfo"],"title":"Structures","generated":true},{"identifiers":["doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiMutliError","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ResultCallback","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/STCResultCallback","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/WebViewResultCallback"],"anchor":"Type-Aliases","title":"Type Aliases","generated":true},{"title":"Enumerations","generated":true,"anchor":"Enumerations","identifiers":["doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiErrorDetail","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiPaymentSource","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiPaymentStatus","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/CreditCardNetwork","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/MetadataValue","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/MoyasarError","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/MoyasarLanguageCode","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/PayButtonType","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/PaymentAuthError","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/PaymentResult","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/WebViewResult"]}],"variants":[{"paths":["\/documentation\/moyasarsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/moyasarsdk"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/STCPayView":{"navigatorTitle":[{"text":"STCPayView","kind":"identifier"}],"url":"\/documentation\/moyasarsdk\/stcpayview","kind":"symbol","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/STCPayView","role":"symbol","type":"topic","title":"STCPayView","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"STCPayView"}]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/STCResultCallback":{"role":"symbol","title":"STCResultCallback","url":"\/documentation\/moyasarsdk\/stcresultcallback","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STCResultCallback"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/STCResultCallback","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"STCResultCallback","kind":"identifier"}]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApplePayPaymentPass":{"kind":"symbol","url":"\/documentation\/moyasarsdk\/applepaypaymentpass","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApplePayPaymentPass","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplePayPaymentPass"}],"title":"ApplePayPaymentPass","role":"symbol","abstract":[],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApplePayPaymentPass"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApiToken":{"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiToken","title":"ApiToken","role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApiToken","kind":"identifier"}],"url":"\/documentation\/moyasarsdk\/apitoken","navigatorTitle":[{"kind":"identifier","text":"ApiToken"}]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApiErrorDetail":{"navigatorTitle":[{"text":"ApiErrorDetail","kind":"identifier"}],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiErrorDetail","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApiErrorDetail","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"title":"ApiErrorDetail","url":"\/documentation\/moyasarsdk\/apierrordetail","type":"topic"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApiApplePaySource":{"kind":"symbol","url":"\/documentation\/moyasarsdk\/apiapplepaysource","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ApiApplePaySource"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApiApplePaySource","kind":"identifier"}],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiApplePaySource","type":"topic","title":"ApiApplePaySource"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApiSTCPaySource":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApiSTCPaySource"}],"url":"\/documentation\/moyasarsdk\/apistcpaysource","kind":"symbol","navigatorTitle":[{"text":"ApiSTCPaySource","kind":"identifier"}],"title":"ApiSTCPaySource","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiSTCPaySource","role":"symbol","abstract":[],"type":"topic"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/MoyasarError":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/MoyasarError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MoyasarError"}],"type":"topic","navigatorTitle":[{"text":"MoyasarError","kind":"identifier"}],"url":"\/documentation\/moyasarsdk\/moyasarerror","title":"MoyasarError"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/StcOtpRequest":{"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/StcOtpRequest","title":"StcOtpRequest","abstract":[],"role":"symbol","url":"\/documentation\/moyasarsdk\/stcotprequest","type":"topic","navigatorTitle":[{"text":"StcOtpRequest","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StcOtpRequest"}],"kind":"symbol"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/PaymentRequest":{"abstract":[],"url":"\/documentation\/moyasarsdk\/paymentrequest","kind":"symbol","title":"PaymentRequest","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PaymentRequest"}],"role":"symbol","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/PaymentRequest","navigatorTitle":[{"kind":"identifier","text":"PaymentRequest"}]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/WebViewPaymentInfo":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/WebViewPaymentInfo","title":"WebViewPaymentInfo","type":"topic","navigatorTitle":[{"text":"WebViewPaymentInfo","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/moyasarsdk\/webviewpaymentinfo","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"WebViewPaymentInfo","kind":"identifier"}]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/MoyasarSdkVersionString":{"title":"MoyasarSdkVersionString","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/MoyasarSdkVersionString","role":"symbol","type":"topic","abstract":[{"text":"Project version string for MoyasarSdk.","type":"text"}],"fragments":[{"text":"MoyasarSdkVersionString","kind":"identifier"}],"url":"\/documentation\/moyasarsdk\/moyasarsdkversionstring","kind":"symbol"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/WebViewResult":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/WebViewResult","navigatorTitle":[{"kind":"identifier","text":"WebViewResult"}],"kind":"symbol","title":"WebViewResult","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebViewResult"}],"abstract":[],"url":"\/documentation\/moyasarsdk\/webviewresult"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApiPaymentSource":{"navigatorTitle":[{"text":"ApiPaymentSource","kind":"identifier"}],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiPaymentSource","kind":"symbol","abstract":[],"url":"\/documentation\/moyasarsdk\/apipaymentsource","title":"ApiPaymentSource","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ApiPaymentSource","kind":"identifier"}],"type":"topic"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApiMutliError":{"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiMutliError","type":"topic","url":"\/documentation\/moyasarsdk\/apimutlierror","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApiMutliError"}],"abstract":[],"title":"ApiMutliError","navigatorTitle":[{"kind":"identifier","text":"ApiMutliError"}]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/CreditCardViewModel":{"navigatorTitle":[{"text":"CreditCardViewModel","kind":"identifier"}],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/CreditCardViewModel","role":"symbol","abstract":[],"url":"\/documentation\/moyasarsdk\/creditcardviewmodel","title":"CreditCardViewModel","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CreditCardViewModel","kind":"identifier"}],"type":"topic"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/STCPayViewModel":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STCPayViewModel"}],"kind":"symbol","title":"STCPayViewModel","navigatorTitle":[{"text":"STCPayViewModel","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/moyasarsdk\/stcpayviewmodel","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/STCPayViewModel","type":"topic"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ResultCallback":{"title":"ResultCallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResultCallback"}],"abstract":[],"role":"symbol","url":"\/documentation\/moyasarsdk\/resultcallback","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ResultCallback","navigatorTitle":[{"text":"ResultCallback","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/PaymentAuthError":{"kind":"symbol","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/PaymentAuthError","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/moyasarsdk\/paymentautherror","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PaymentAuthError","kind":"identifier"}],"title":"PaymentAuthError","navigatorTitle":[{"text":"PaymentAuthError","kind":"identifier"}]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/PaymentAuthView":{"role":"symbol","title":"PaymentAuthView","url":"\/documentation\/moyasarsdk\/paymentauthview","kind":"symbol","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/PaymentAuthView","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PaymentAuthView"}],"navigatorTitle":[{"text":"PaymentAuthView","kind":"identifier"}],"abstract":[]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/CreditCardView":{"kind":"symbol","url":"\/documentation\/moyasarsdk\/creditcardview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreditCardView"}],"type":"topic","navigatorTitle":[{"text":"CreditCardView","kind":"identifier"}],"title":"CreditCardView","role":"symbol","abstract":[{"type":"text","text":"A view that displays a credit card payment interface."}],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/CreditCardView"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApiPaymentStatus":{"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiPaymentStatus","type":"topic","title":"ApiPaymentStatus","abstract":[],"navigatorTitle":[{"text":"ApiPaymentStatus","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApiPaymentStatus"}],"url":"\/documentation\/moyasarsdk\/apipaymentstatus"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/MoyasarLanguageCode":{"url":"\/documentation\/moyasarsdk\/moyasarlanguagecode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MoyasarLanguageCode"}],"type":"topic","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/MoyasarLanguageCode","title":"MoyasarLanguageCode","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MoyasarLanguageCode"}],"role":"symbol"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApplePayService":{"role":"symbol","title":"ApplePayService","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApplePayService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplePayService"}],"abstract":[],"url":"\/documentation\/moyasarsdk\/applepayservice","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplePayService"}]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApplePayPaymentMethod":{"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApplePayPaymentMethod","kind":"symbol","abstract":[],"url":"\/documentation\/moyasarsdk\/applepaypaymentmethod","title":"ApplePayPaymentMethod","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"ApplePayPaymentMethod","kind":"identifier"}],"navigatorTitle":[{"text":"ApplePayPaymentMethod","kind":"identifier"}],"type":"topic"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/WebViewResultCallback":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"WebViewResultCallback","kind":"identifier"}],"kind":"symbol","type":"topic","title":"WebViewResultCallback","role":"symbol","url":"\/documentation\/moyasarsdk\/webviewresultcallback","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/WebViewResultCallback","navigatorTitle":[{"kind":"identifier","text":"WebViewResultCallback"}]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/PaymentService":{"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/PaymentService","kind":"symbol","role":"symbol","url":"\/documentation\/moyasarsdk\/paymentservice","navigatorTitle":[{"text":"PaymentService","kind":"identifier"}],"title":"PaymentService","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PaymentService","kind":"identifier"}]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApiPayment":{"url":"\/documentation\/moyasarsdk\/apipayment","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApiPayment"}],"type":"topic","title":"ApiPayment","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApiPayment"}],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiPayment"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk":{"kind":"symbol","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk","title":"MoyasarSdk","type":"topic","role":"collection","abstract":[],"url":"\/documentation\/moyasarsdk"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/MoyasarSdkVersionNumber":{"type":"topic","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/MoyasarSdkVersionNumber","fragments":[{"kind":"identifier","text":"MoyasarSdkVersionNumber"}],"url":"\/documentation\/moyasarsdk\/moyasarsdkversionnumber","title":"MoyasarSdkVersionNumber","kind":"symbol","abstract":[{"text":"Project version number for MoyasarSdk.","type":"text"}],"role":"symbol"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/PayButtonType":{"type":"topic","role":"symbol","url":"\/documentation\/moyasarsdk\/paybuttontype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PayButtonType"}],"title":"PayButtonType","navigatorTitle":[{"text":"PayButtonType","kind":"identifier"}],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/PayButtonType","abstract":[],"kind":"symbol"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/CreditCardNetwork":{"navigatorTitle":[{"text":"CreditCardNetwork","kind":"identifier"}],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/CreditCardNetwork","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CreditCardNetwork"}],"kind":"symbol","role":"symbol","abstract":[],"title":"CreditCardNetwork","url":"\/documentation\/moyasarsdk\/creditcardnetwork","type":"topic"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApplePayToken":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApplePayToken"}],"url":"\/documentation\/moyasarsdk\/applepaytoken","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ApplePayToken"}],"title":"ApplePayToken","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApplePayToken","role":"symbol","abstract":[],"type":"topic"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApiError":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ApiError","kind":"identifier"}],"title":"ApiError","url":"\/documentation\/moyasarsdk\/apierror","role":"symbol","navigatorTitle":[{"text":"ApiError","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiError","type":"topic"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApiPaymentRequest":{"title":"ApiPaymentRequest","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ApiPaymentRequest","kind":"identifier"}],"type":"topic","url":"\/documentation\/moyasarsdk\/apipaymentrequest","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiPaymentRequest","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ApiPaymentRequest","kind":"identifier"}]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/MetadataValue":{"title":"MetadataValue","navigatorTitle":[{"kind":"identifier","text":"MetadataValue"}],"role":"symbol","type":"topic","url":"\/documentation\/moyasarsdk\/metadatavalue","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MetadataValue"}],"abstract":[],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/MetadataValue","kind":"symbol"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/PaymentResult":{"kind":"symbol","url":"\/documentation\/moyasarsdk\/paymentresult","title":"PaymentResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentResult"}],"abstract":[],"identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/PaymentResult","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PaymentResult"}],"role":"symbol"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApiTokenRequest":{"url":"\/documentation\/moyasarsdk\/apitokenrequest","role":"symbol","navigatorTitle":[{"text":"ApiTokenRequest","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiTokenRequest","type":"topic","title":"ApiTokenRequest","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApiTokenRequest","kind":"identifier"}]},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/ApiCreditCardSource":{"type":"topic","title":"ApiCreditCardSource","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApiCreditCardSource"}],"navigatorTitle":[{"kind":"identifier","text":"ApiCreditCardSource"}],"abstract":[],"role":"symbol","url":"\/documentation\/moyasarsdk\/apicreditcardsource","kind":"symbol","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/ApiCreditCardSource"},"doc://com.moyasar.MoyasarSdk/documentation/MoyasarSdk/MoyasarLanguageManager":{"type":"topic","identifier":"doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/MoyasarLanguageManager","kind":"symbol","url":"\/documentation\/moyasarsdk\/moyasarlanguagemanager","navigatorTitle":[{"kind":"identifier","text":"MoyasarLanguageManager"}],"title":"MoyasarLanguageManager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MoyasarLanguageManager"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/MoyasarSdkVersionNumber","doc:\/\/com.moyasar.MoyasarSdk\/documentation\/MoyasarSdk\/MoyasarSdkVersionString"],"title":"Variables","anchor":"Variables"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"}]}]}